repos:
  - repo: local
    hooks:
      - id: lock
        name: pipenv lock
        stages: [push]
        language: system
        entry: pipenv lock
        files: Pipfile
        pass_filenames: False

